<!DOCTYPE html>
<html encoding="utf-8" lang="nl">
<?php require_once 'head.php'; ?>
    <body>

        <main>
            <?php require_once '../../header.php';?>
            <div class="container"> 
                <div class="darthvaderPage">
                    <h1>Darth Vader</h1>
                    <div class="InfoImg">
                        <img src="../../img/darthvader-starwars.jpg" alt="Img Darth Vader">
                    </div>
                    <div class="darthvadertext">
                        <p><b>Darth Vader</b> is a central character in the Star Wars universe, appearing as the central antagonist of the original trilogy.</p>
                        <p>He is the Sith Lord persona of the fallen Jedi Knight Anakin Skywalker after his turn to the dark side. He remains the central antagonist until the events of Return of the Jedi, when he eventually redeems himself to save his son, Luke Skywalker from his master Darth Sidious, fulfilling the Prophecy as the Chosen One.
                        <p>After Anakin Skywalker finally embraced his inner darkness, the persona of Anakin ceased to exist, as the Darth Vader persona overtook him almost completely. Unlike most members of the Sith Order, Vader is not only capable of acknowledging his mistakes, but learning from them as well.</p>
                        <p>Vader became emotionally traumatized by the experience of the events on Mustafar. Vader is now terrifying, driven by rage, and his overconfidence has been further greatly amplified to the point of arrogance. However, after his defeat and mutilation on Mustafar at the hands of Obi-Wan Kenobi, he is no longer as arrogant and overconfident as he previously was. Although he eventually regained confidence in himself, it never came to the point of being outwardly arrogant or cocky.</p>
                        <p>Vader remains an impatient man, albeit to a far less extent, but generally presents himself as calm and level-headed. He rarely loses his temper and usually has good control over his emotions (something he was not able to do in his youth), but he has an extremely low tolerance for failure and any form of betrayal. Despite this, he is able to tolerate failure from his troops to a certain extent, although he becomes known for frequently killing his own men for even the slightest mistake. He also does not get along well at all with naval officers in the Imperial military. He has little to no tolerance for incompetence or for those who disrespect him for no clear reason, nearly choking Admiral Conan Antonio Motti to death when he disrespected Vader and challenged his powers of the Force. Vader telekinetically strangled Admiral Kendal Ozzel and Captain Lorth Needa for their incompetence. Many higher-ranking officers came to despise the Sith Lord and his "sorcerer's ways" for no clear reason.</p>
                        <p>Despite Vader's negative relationship with some higher-ranking officers in the military, he does get along reasonably well with the Stormtroopers because of his front line leadership. One reason Vader became popular with the troops that served under him is his willingness to fight in the front line, and not expect of anyone anything he was not willing to do himself.</p>
                        <p>As Supreme Commander within the ranks of the Imperial Army of the Galactic Empire, Vader is renowned for his leadership skills and admired by clones, middle/low-ranking officers, Sith, and politicians alike.</p>
                        <p>Despite what Vader's actions causes upon both himself and the galaxy, he apparently believes he is doing what is good for the galaxy, claiming not to feel regret. However, he actually secretly feels enormous shame and remorse for his actions, whether he wants to admit it or not. His feelings of guilt are so much that he develops a deep self-loathing and even nearly commits suicide at one point.</p>
                        <p>Vader is determined to never talk about his old life, wanting to distance himself from his painful past as best as possible. As a result, he detests anything that reminds him of his former-self, which he deems to be weak. It is for this reason that he showed no desire to restore the bond he once shared with his former apprentice and friend Ahsoka Tano, as she is a living memory of everything he once was, and in his own twisted way, he became angry at her for leaving him and the Jedi Order, something he perceived later on as a form of betrayal. Upon their fateful reunion, he did offer to spare her if she told him where the other lost Jedi were hiding, but cruelly resolved to kill her when she refused, and even when she found out he was indeed her former mentor and showed him compassion.</p>
                        <p>Due to Vader's former status as a slave, he has distress when the concept of slavery is brought up, despite the fact that the Empire made slavery legal again. He also can not return to his home planet Tatooine, as the planet is a painful reminder of him losing his mother, Shmi Skywalker. It was only after he found out about the existence of his son, Luke Skywalker, that Vader was able to muster the ability to return to Tatooine once more, and only because it was in search of information regarding his son.</p>
                        <p>Vader is cold, brutal, and ruthless towards his enemies, perfectly willing to terrorize, torture, and even murder them in cold-blood, although he does not take pleasure out of it. The exception to this might have been during his trip to Tatooine in search of information regarding his son, Luke Skywalker, during which he slaughtered an entire tribe of Tusken Raiders (much as he had as Anakin) either out of vengeance or pleasure for what they did to his mother.</p>
                        <p>Vader is seemingly unfailingly loyal to his master, being Sheev Palpatine the closest thing he has to a friend. However, in truth he secretly hates his master for deceiving him and ruining his life, even planning to overthrow him one day with his own apprentice. The only reason why Vader continued to serve Palpatine after losing his wife, was because the Emperor was all he had left of his former life as Anakin Skywalker and was the only one that would accept him. Ultimately, Vader is only truly loyal to the people he still cared about (like his son, Luke Skywalker), which is seen with him doing everything possible to protect his son from Palpatine.</p>
                        <p>Despite of these negative traits, Vader later proves that there was still good left in him. Upon discovering the existence of his son, Luke Skywalker, Vader became emotionally conflicted, unsure whether to continue serving his master or overthrow him with his son. He displayed a sense of compassion for Luke, revealing that some hint of him still had love for his family. This attachment ultimately led to his redemption.</p>
                        <p>Before the Battle of Endor had begun, Vader strongly believed that he was irredeemable and there was no good left in him. This belief was so strong that in a mental battle between his good and evil halves brought about after once being defeated by a powerful enemy. The evil Vader persona of his personality battled and destroyed the Anakin persona that represented his good side. However, when his son, Luke, was being tortured by Palpatine, he finally broke away from the dark side. At this point, Vader ceased to exist and Anakin returned in full force.</p>
                        <p>When Anakin sacrifices his life to save his son, before succumbing to the injuries he received from Palpatine, Anakin reconciled with Luke, and thanked his son for never giving up hope in saving him. He then died peacefully, becoming one with the Force.</p>
                    </div>
                </div>
            </div>
        </main>
        <footer>
        </footer>
    </body>
</html>