<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h1>Timoty Dalton</h1>
    <div class="timotydaltonimg">
    <img src="img" alt="Img Timoty Dalton">
</div>
    <div class="timotydaltontext">
    <p><b>Timothy Dalton</b> was born in Colwyn Bay, Wales, UK, he is of mixed English and Italian-Irish ancestry. Soon after his birth, the family moved to Belper, Derbyshire, England, UK. He became interested in acting in his teenage years, and left school in 1962 to enrol in the Royal Academy of Dramatic Art and tour with the National Youth Theatre in the summer. He did not complete his RADA studies, leaving the academy in 1966 to join the ensemble of the Birmingham Repertory Theatre. He quickly moved to television, working mainly with BBC, and in 1968 made his film debut in The Lion in Winter, the first of several period dramas.</p>
    <p>After a few more films, Dalton took a break in 1971 to concentrate on the theatre, performing with the Royal Shakespeare Company and other troupes throughout the world. With the exception of the 1975 film Permission to Kill, he remained a theatre actor until 1978. That year he starred in Sextette, hailing his return to cinema and the beginning of his American career. While in the United States, Dalton worked mainly in television, although he starred in several European films and gave notable performances for the BBC.</p>
    <p>In 1986, after Roger Moore's retirement from the James Bond role, Dalton was approached to replace him but obligations to the film Brenda Starr kept him from accepting the role. Sam Neill was then screentested for the part of Bond but was ultimately rejected by "Cubby" Broccoli. Pierce Brosnan was then approached for the role, but rescinded because of his commitment to the television revival of Remington Steele. In the ensuing time, Dalton had completed the filming of Brenda Starr and was now able to accept the role of Bond.</p>
    <p>Previously, Dalton had been offered the role in 1969 to replace Sean Connery after You Only Live Twice, but turned it down feeling he was too young for the role and because of what he felt was an imposing legacy left behind by Connery. He was approached again following Connery's second departure after Diamonds Are Forever but again declined, citing the same reasons. He was offered the part a third time in 1981 when Roger Moore decided to retire from the character prior to For Your Eyes Only; Dalton was apparently all but signed to the role when Moore decided to continue at the last moment. Work commitments made him again refuse the role in 1986, but when asked again, he finally agreed to appear in three James Bond films. The first, The Living Daylights (1987) was successful and grossed more than the previous two Roger Moore Bond films as well as contemporary box office rivals such as Die Hard and Lethal Weapon.</p>
    <p>The second film, Licence to Kill (1989) did not perform as well at the U.S. box office, partly due to a lacklustre marketing campaign, after the title of the film was abruptly changed from Licence Revoked, and partly because it was released in competition with other action blockbusters Batman, Indiana Jones and the Last Crusade, Lethal Weapon 2, Ghost Busters II, Honey I Shrunk the Kids and Back to the Future Part II over the summer of 1989. As a direct result of the latter, no Bond movie since has been released over the summer months. However, MGM reported a net profit of $28.2 million for the film. </p>
    <p>Dalton's third Bond film (rumoured title: The Property of A Lady) was due for a 1991 release but its production was scuttled by internecine corporate litigation between Danjaq, LLC, the copyright holder of James Bond on screen and MGM/United Artists (Giancarlo Parretti), the financier and distributor of the series. In 1994, tired of waiting for a film that seemed as though it would never happen, Dalton officially dropped the James Bond role, re-opening the door for Pierce Brosnan.</p>
    <p>Dalton's portrayal of Bond - darker, more grittily realistic and truer to the original character as portrayed in Fleming's novels - was something of a double-edged sword. Critics welcomed a more serious interpretation after more than a decade of Roger Moore's lighthearted approach but the reaction of Moore aficionados and those who had grown up with Moore as their Bond during his 15 year tenure and were generally unfamiliar with Ian Fleming's original novels was mixed. Despite the contemporary criticism, rumours persist to this day that Dalton had always been high on "Cubby" Broccoli's list of ideal Bond actors. More recent evaluation has warmed somewhat to Dalton's brief tenure, with some critics noting the similarities between his gritty performance and that of Daniel Craig.</p>
</div>
</body>
</html>